title: 'Skye prod'
default_lang: fr
author:
  name: 'Virgil Roger'
  email: roger.virgil@gmail.com
taxonomies:
  - category
  - tag
  - pagetype
summary:
  enabled: true
  format: short
  size: 300
  delimiter: '==='
blog:
  route: /blog
# menu:
#     - url: '#'
#       text: 'Sign Up'
#       classes: 'button primary'
