title: 'Skye prod'
default_lang: fr
author:
  name: 'OMG Design'
  email: contact@omg-design.com
taxonomies:
  - category
  - tag
  - pagetype
summary:
  enabled: true
  format: short
  size: 300
  delimiter: '==='
blog:
  route: /blog
# menu:
#     - url: '#'
#       text: 'Sign Up'
#       classes: 'button primary'
